Import setuptools.config lazily to work with old setuptools
setuptools.config.read_configuration() Allow was added in setuptools
38.2.5. Some environments may be on an older version of setuptools, but
are otherwise compatible with django-decorator-include. The
read_configuration() function is only required when developing in the
source directory; not for the installed library. To easily workaround
this, import it only as need.

Fixes import error:

      from setuptools.config import read_configuration
  ModuleNotFoundError: No module named 'setuptools.config'